name: Ashbright
markdown: kramdown
highlighter: rouge #
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Setup
title:               Ashbright
tagline:             Strategic communications
url:                 https://wearethoughtfox.github.io/ashbright/
baseurl:

