name: Ashbright
markdown: kramdown
highlighter: rouge #
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Setup
title:               Ashbright
tagline:             Strategic communications
url:                 https://www.ashbright.com

collections:
  situations:
    output: true
    permalink: /:collection/:name

